### ISSUE TITLE
XMLChoiceCodingKey In conjunction with an attribute

### ISSUE THREAD

**Issue by henkvanderspek** [CoreOffice/XMLCoder#237]
Hi, great library. Many thanks 🙌
One thing I can't get to work. A choice element with support for an attribute. If I add an attribute to the choice and the xml, it's always ignored by the decoder.

```
<root id="100">
  <int>5</int>
  <string>foo</string>
  <int>6</int>
  <string>bar</string>
</root>
```

**Comment by henkvanderspek** [comment]
Never mind. I looked at the wrong level for the property 🤦

**Comment by brutella** [comment]
I'm also having troubling decoding such XML structure. How did you manage to resolve that?
