### ISSUE TITLE
Add DOCTYPE tag

### ISSUE THREAD

**Issue by bfreeTax** [CoreOffice/XMLCoder#252]
I need to encode my structure and add **`DOCTYPE`** just after `xml version="1.0" ...` tag, this is the example XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE myService PUBLIC "-//Domain//DTD MyService v1//EN" "http://dtd.domain.com/myService_v1.dtd">
<myService>
        <order>
                <value>My important value</value>
       </order>
</myService>
```
For`xml version="1.0" ...` I use XMLHeader, but I can't find anything for "inject" `DOCTYPE`. Is that even posible ?

**Comment by Joannis** [comment]
I'm not the creator - but I am an active maintainer of the library. I don't think this is currently possible, but I'll check out if we can fix that.

**Comment by Joannis** [comment]
Hey @bfreeTax, I've added a draft PR that should work for you. I've yet to add tests, before reviewing & merging it. At least you have something to try out for now.

**Comment by bfreeTax** [comment]
> Hey @bfreeTax, I've added a draft PR that should work for you. I've yet to add tests, before reviewing & merging it. At least you have something to try out for now.

Hey @Joannis tested and works perfect!! Thanks for taking the time!
